### ISSUE TITLE
Regarding the test phase, whether the output is a fused mask or a branch mask？

### ISSUE THREAD

**Issue by yike5022** [lofrienger/S2ME#1]
Hello, I have a question. Regarding the test phase, whether the output is a fused mask or a branch mask？y_hat_spa or y_hat_s2?

**Comment by lofrienger** [comment]
> Hello, I have a question. Regarding the test phase, whether the output is a fused mask or a branch mask？y_hat_spa or y_hat_s2?

@yike5022 
Hi, we use the output from the spatial branch for testing and fair comparison with other methods.

**Comment by yike5022** [comment]
Thank you for your reply!

---- Replied Message ----
| From | An ***@***.***> |
| Date | 11/21/2023 16:17 |
| To | lofrienger/S2ME ***@***.***> |
| Cc | yike5022 ***@***.***>,
Mention ***@***.***> |
| Subject | Re: [lofrienger/S2ME] Regarding the test phase, whether the output is a fused mask or a branch mask？ (Issue #1) |

Hello, I have a question. Regarding the test phase, whether the output is a fused mask or a branch mask？y_hat_spa or y_hat_s2?

@yike5022
Hi, we use the output from the spatial branch for testing and fair comparison with other methods.
