### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by 1456214718** [lofrienger/S2ME#2]
想问分布外泛化，只需要将数据集的位置改变就可以了吗，小白

**Comment by lofrienger** [comment]
@1456214718 
As long as the folder structure of your external dataset follows the in-distribution dataset, just replacing the dataset location should be fine to assess the OOD performance.

**Comment by 1456214718** [comment]
意思就是KvasirDataset这个数据集也要像SUN-SEG数据集一样，分出训练、测试和验证，然后和做成和data/polyp一样吗

**Comment by lofrienger** [comment]
@1456214718 
Hi, you don't need to split the dataset. 
We test on all 1000 images of the [kvasir-seg](https://datasets.simula.no/kvasir-seg/) dataset.

**Comment by 1456214718** [comment]
测试？意思就是这个数据集只要测试，不需要训练和验证吗？

**Comment by lofrienger** [comment]
@1456214718 
Yes, this can also be considered as a zero-shot out-of-distribution (OOD) transfer evaluation.

**Comment by 1456214718** [comment]
可是CVCDataset这个数据库为什么测试的时候，总会出现这个错误stack expects each tensor to be equal size,but got [3,244,244]at entry 0 and [244,244,3]at entry 4，这个错误困扰我好久，不太会解决

**Comment by lofrienger** [comment]
@1456214718 
Hi, the error arises because the two tensors have different dimension orders (CHW and HWC).
I have no idea if you can test with other datasets but not this one.
Perhaps you can paste more details here, like which lines of code, so that I can offer help.

**Comment by 1456214718** [comment]
from dataloaders.dataset_polyp import (CVCDataset, trsf_train_image_224,
                                       trsf_valid_image_224)
parser.add_argument('--ds_root', type=str,
                    default='../dataset/CVCDataset', help='dataset root dir')
db_train = CVCDataset(ds_root=args.ds_root, transform=trsf_train_image_224,save='False')
在你代码的基础上就改了这些，其他没动，而且这个数据集我也是下载您提供的链接，我不知道为什么会出现这种情况，KvasirDataset数据集没有问题了

**Comment by lofrienger** [comment]
@1456214718 
Hi, for testing, you should use **trsf_valid_image_224** rather than **trsf_train_image_224** as the transformation.

**Comment by 1456214718** [comment]
好的，谢谢您，除了这个还需改动哪里吗

**Comment by lofrienger** [comment]
@1456214718 Looks fine with your provided code.
