### ISSUE TITLE
Perhaps you can provide the full eval-result running on the SUNSEG dataset? They are the results of Smeasure, maxEm, wFmeasure, maxDice, maxIou on four test datasets.

### ISSUE THREAD

**Issue by yike5022** [lofrienger/S2ME#7]

**Comment by lofrienger** [comment]
Sorry, but I don't have time to test with other metrics...

**Comment by yike5022** [comment]
thank you ，I will try to solve it

---- Replied Message ----
| From | An ***@***.***> |
| Date | 07/10/2024 18:01 |
| To | lofrienger/S2ME ***@***.***> |
| Cc | yike5022 ***@***.***>,
Author ***@***.***> |
| Subject | Re: [lofrienger/S2ME] Perhaps you can provide the full eval-result running on the SUNSEG dataset? They are the results of Smeasure, maxEm, wFmeasure, maxDice, maxIou on four test datasets. (Issue #7) |

Sorry, but I don't have time to test with other metrics...
